#!/usr/bin/env python
import sys
import optparse

version = '0.1'

def main():
    parser = optparse.OptionParser(version='%%prog %s' % version)

    options, args = parser.parse_args()
    return 0

if __name__ == '__main__':
    sys.exit(main())
