#!/usr/bin/env python3
#
# Test `git-publish --setup`
#
# Copyright 2019 Red Hat, Inc.
#
# Authors:
#   Eduardo Habkost <ehabkost@redhat.com>
#
# This work is licensed under the MIT License.  Please see the LICENSE file or
# http://opensource.org/licenses/MIT.

from test_utils import *

# note that 'git config' is not in the passthrough list of fake_git,
# so this is safe to run:
git_publish('--setup')
assert last_git_command() == ['config', '--global', 'alias.publish',
                              '!' + git_publish_path()]
